apiVersion: apps/v1
kind: Deployment
metadata:
  name: rzvcv
  namespace: cvrzv
  labels:
    app: rzvcv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rzvcv
  template:
    metadata:
      labels:
        app: rzvcv
    spec:
      containers:
      - name: rzvcvctn
        image: thorgate.local:5000/cv:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: rzvcv
  namespace: cvrzv
spec:
  selector:
    app: rzvcv
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rzvcv-ingress
  namespace: cvrzv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: razvanvalentingrigoras.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rzvcv
            port:
              number: 3000
